### ISSUE TITLE
Option to add a model identifier to the search result

### ISSUE THREAD

**Issue by mrkalmdn** [protonemedia/laravel-cross-eloquent-search#41] opened 2021-12-03 10:23 UTC
As the title says, do we have an option to add an identifier to the search result? Just to know which model we are currently iterating.

For example

```json

{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "video_id": null,
      "title": "foo",
      "published_at": null,
      "created_at": "2021-12-03T09:39:10.000000Z",
      "updated_at": "2021-12-03T09:39:10.000000Z",
      "type": "Post"
    },
    {
      "id": 1,
      "title": "foo",
      "subtitle": null,
      "published_at": null,
      "created_at": "2021-12-03T09:39:10.000000Z",
      "updated_at": "2021-12-03T09:39:10.000000Z",
      "type": "Video"
    }
  ]
}

```

**Comment by pascalbaljet** [comment] 2021-12-03 14:44
Duplicate of https://github.com/protonemedia/laravel-cross-eloquent-search/issues/5

**Closed by pascalbaljet** 2021-12-03 14:44 UTC

**Comment by mrkalmdn** [comment] 2021-12-04 05:39
Nice! Thanks, @pascalbaljet!
